title: TPM Cheat sheets
description: supporting materials for delivery selection
theme: jekyll-theme-cayman
show_downloads: false

plugins:
  - jekyll-last-modified-at

last-modified-at:
    date-format: '%d-%b-%y'