title: TPM Cheat sheets
description: supporting materials for delivery selection
theme: jekyll-theme-cayman
show_downloads: false

plugins:
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%Y-%m-%d %H:%M'